-- =============================================
-- SISTEMA CONTABLE - Script completo
-- =============================================

-- 1. Crear y usar la base de datos
CREATE DATABASE SistemaContable;
GO
USE SistemaContable;
GO

-- 2. METODO_PAGO (va primero porque TRANSACCION la referencia)
CREATE TABLE METODO_PAGO (
    COD_METODO_PAGO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION     VARCHAR(50)
);
GO

-- 3. CUENTA
CREATE TABLE CUENTA (
    COD_CUENTA         INT PRIMARY KEY,
    NOMBRE_CUENTA      VARCHAR(100) NOT NULL,
    GRUPO_CUENTA       VARCHAR(50),
    TIPO_CUENTA        VARCHAR(50),
    SALDO_DEBE_CUENTA  DECIMAL(18,2) DEFAULT 0,
    SALDO_HABER_CUENTA DECIMAL(18,2) DEFAULT 0,
    ESTADO_CUENTA      BIT DEFAULT 1
);
GO

-- 4. ASIENTO
CREATE TABLE ASIENTO (
    COD_ASIENTO             INT PRIMARY KEY IDENTITY(1,1),
    FECHA_REGISTRO_ASIENTO  DATE NOT NULL,
    GLOSA_ASIENTO           VARCHAR(255),
    TOTAL_CUENTAS_AFECTADAS INT,
    SALDO_DEBE_ASIENTO      DECIMAL(18,2) DEFAULT 0,
    SALDO_HABER_ASIENTO     DECIMAL(18,2) DEFAULT 0,
    ESTADO_ASIENTO          VARCHAR(20) DEFAULT 'PENDIENTE'
);
GO

-- 5. TRANSACCION
CREATE TABLE TRANSACCION (
    COD_TRANSACCION            INT PRIMARY KEY IDENTITY(1,1),
    COD_ASIENTO                INT FOREIGN KEY REFERENCES ASIENTO(COD_ASIENTO),
    COD_METODO_PAGO            INT FOREIGN KEY REFERENCES METODO_PAGO(COD_METODO_PAGO),
    TIPO_TRANSACCION           VARCHAR(50),
    SUB_TIPO_TRANSACCION       VARCHAR(50),
    FECHA_REGISTRO_TRANSACCION DATE,
    MONTO_TRANSACCION          DECIMAL(18,2)
);
GO

-- 6. PARTIDA
CREATE TABLE PARTIDA (
    COD_PARTIDA     INT PRIMARY KEY IDENTITY(1,1),
    COD_ASIENTO     INT FOREIGN KEY REFERENCES ASIENTO(COD_ASIENTO),
    COD_CUENTA      INT FOREIGN KEY REFERENCES CUENTA(COD_CUENTA),
    TIPO_MOVIMIENTO CHAR(1) CHECK (TIPO_MOVIMIENTO IN ('D','H')),
    MONTO_PARTIDA   DECIMAL(18,2) NOT NULL,
    FECHA_PARTIDA   DATETIME DEFAULT GETDATE()
);
GO

-- 7. ESTADO_FINANCIERO
CREATE TABLE ESTADO_FINANCIERO (
    COD_ESTADO_FINANCIERO   INT PRIMARY KEY IDENTITY(1,1),
    TIPO_ESTADO_FINANCIERO  VARCHAR(50),
    ESTADO_FINANCIERO       VARCHAR(50),
    SALDO_ESTADO_FINANCIERO DECIMAL(18,2) DEFAULT 0,
    FECHA_CORTE             DATE
);
GO

-- 8. REGLA_NEGOCIO
CREATE TABLE REGLA_NEGOCIO (
    COD_REGLA             INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION_REGLA     VARCHAR(255),
    COD_CUENTA            INT FOREIGN KEY REFERENCES CUENTA(COD_CUENTA),
    COD_ESTADO_FINANCIERO INT FOREIGN KEY REFERENCES ESTADO_FINANCIERO(COD_ESTADO_FINANCIERO),
    OPERACION             CHAR(1) CHECK (OPERACION IN ('+','-'))
);
GO

-- 9. BALANCE_COMPROBACION
CREATE TABLE BALANCE_COMPROBACION (
    COD_BALANCE       INT PRIMARY KEY IDENTITY(1,1),
    MES               INT,
    ANIO              INT,
    SALDO_DEBE_TOTAL  DECIMAL(18,2),
    SALDO_HABER_TOTAL DECIMAL(18,2),
    ESTADO_BALANCE    VARCHAR(20)
);
GO

-- 10. BALANCE_COMPROBACION_DETALLE
CREATE TABLE BALANCE_COMPROBACION_DETALLE (
    COD_DETALLE INT PRIMARY KEY IDENTITY(1,1),
    COD_BALANCE INT FOREIGN KEY REFERENCES BALANCE_COMPROBACION(COD_BALANCE),
    COD_CUENTA  INT FOREIGN KEY REFERENCES CUENTA(COD_CUENTA),
    SALDO_DEBE  DECIMAL(18,2),
    SALDO_HABER DECIMAL(18,2)
);
GO

-- 11. VISTA MAYOR
CREATE VIEW MAYOR AS
SELECT
    P.COD_CUENTA,
    C.NOMBRE_CUENTA,
    A.FECHA_REGISTRO_ASIENTO,
    A.GLOSA_ASIENTO,
    CASE WHEN P.TIPO_MOVIMIENTO = 'D' THEN P.MONTO_PARTIDA ELSE 0 END AS DEBE,
    CASE WHEN P.TIPO_MOVIMIENTO = 'H' THEN P.MONTO_PARTIDA ELSE 0 END AS HABER
FROM PARTIDA P
JOIN ASIENTO A ON P.COD_ASIENTO = A.COD_ASIENTO
JOIN CUENTA  C ON P.COD_CUENTA  = C.COD_CUENTA;
GO

-- 12. Datos base
INSERT INTO METODO_PAGO (DESCRIPCION) VALUES ('CONTADO'), ('CREDITO');
GO